#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRM")]
	public partial class HRM_DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDEPARTMENT(DEPARTMENT instance);
    partial void UpdateDEPARTMENT(DEPARTMENT instance);
    partial void DeleteDEPARTMENT(DEPARTMENT instance);
    partial void InsertPOSITION(POSITION instance);
    partial void UpdatePOSITION(POSITION instance);
    partial void DeletePOSITION(POSITION instance);
    partial void InsertBLOOD_GROUP(BLOOD_GROUP instance);
    partial void UpdateBLOOD_GROUP(BLOOD_GROUP instance);
    partial void DeleteBLOOD_GROUP(BLOOD_GROUP instance);
    partial void InsertLANGUAGE(LANGUAGE instance);
    partial void UpdateLANGUAGE(LANGUAGE instance);
    partial void DeleteLANGUAGE(LANGUAGE instance);
    partial void InsertGENDER(GENDER instance);
    partial void UpdateGENDER(GENDER instance);
    partial void DeleteGENDER(GENDER instance);
    partial void InsertBRANCH(BRANCH instance);
    partial void UpdateBRANCH(BRANCH instance);
    partial void DeleteBRANCH(BRANCH instance);
    partial void InsertPASS(PASS instance);
    partial void UpdatePASS(PASS instance);
    partial void DeletePASS(PASS instance);
    partial void InsertACCESS(ACCESS instance);
    partial void UpdateACCESS(ACCESS instance);
    partial void DeleteACCESS(ACCESS instance);
    partial void InsertSTATUS(STATUS instance);
    partial void UpdateSTATUS(STATUS instance);
    partial void DeleteSTATUS(STATUS instance);
    partial void InsertEMP_INFO(EMP_INFO instance);
    partial void UpdateEMP_INFO(EMP_INFO instance);
    partial void DeleteEMP_INFO(EMP_INFO instance);
    partial void InsertWORK_TYPE(WORK_TYPE instance);
    partial void UpdateWORK_TYPE(WORK_TYPE instance);
    partial void DeleteWORK_TYPE(WORK_TYPE instance);
    partial void InsertEMP_WORK_INFO(EMP_WORK_INFO instance);
    partial void UpdateEMP_WORK_INFO(EMP_WORK_INFO instance);
    partial void DeleteEMP_WORK_INFO(EMP_WORK_INFO instance);
    partial void InsertATTENDANCE(ATTENDANCE instance);
    partial void UpdateATTENDANCE(ATTENDANCE instance);
    partial void DeleteATTENDANCE(ATTENDANCE instance);
    partial void InsertNOTICE(NOTICE instance);
    partial void UpdateNOTICE(NOTICE instance);
    partial void DeleteNOTICE(NOTICE instance);
    partial void InsertT_SHIRT_SIZE(T_SHIRT_SIZE instance);
    partial void UpdateT_SHIRT_SIZE(T_SHIRT_SIZE instance);
    partial void DeleteT_SHIRT_SIZE(T_SHIRT_SIZE instance);
    partial void InsertT_SHIRT_STOCK(T_SHIRT_STOCK instance);
    partial void UpdateT_SHIRT_STOCK(T_SHIRT_STOCK instance);
    partial void DeleteT_SHIRT_STOCK(T_SHIRT_STOCK instance);
    partial void InsertT_SHIRT_NAME(T_SHIRT_NAME instance);
    partial void UpdateT_SHIRT_NAME(T_SHIRT_NAME instance);
    partial void DeleteT_SHIRT_NAME(T_SHIRT_NAME instance);
    partial void InsertT_SHIRT_STATE(T_SHIRT_STATE instance);
    partial void UpdateT_SHIRT_STATE(T_SHIRT_STATE instance);
    partial void DeleteT_SHIRT_STATE(T_SHIRT_STATE instance);
    partial void InsertSALE_T_SHIRT(SALE_T_SHIRT instance);
    partial void UpdateSALE_T_SHIRT(SALE_T_SHIRT instance);
    partial void DeleteSALE_T_SHIRT(SALE_T_SHIRT instance);
    #endregion
		
		public HRM_DataClassesDataContext() : 
				base(global::DAL.Properties.Settings.Default.HRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HRM_DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRM_DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRM_DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRM_DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DEPARTMENT> DEPARTMENTs
		{
			get
			{
				return this.GetTable<DEPARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<POSITION> POSITIONs
		{
			get
			{
				return this.GetTable<POSITION>();
			}
		}
		
		public System.Data.Linq.Table<BLOOD_GROUP> BLOOD_GROUPs
		{
			get
			{
				return this.GetTable<BLOOD_GROUP>();
			}
		}
		
		public System.Data.Linq.Table<LANGUAGE> LANGUAGEs
		{
			get
			{
				return this.GetTable<LANGUAGE>();
			}
		}
		
		public System.Data.Linq.Table<GENDER> GENDERs
		{
			get
			{
				return this.GetTable<GENDER>();
			}
		}
		
		public System.Data.Linq.Table<BRANCH> BRANCHes
		{
			get
			{
				return this.GetTable<BRANCH>();
			}
		}
		
		public System.Data.Linq.Table<PASS> PASSes
		{
			get
			{
				return this.GetTable<PASS>();
			}
		}
		
		public System.Data.Linq.Table<ACCESS> ACCESSes
		{
			get
			{
				return this.GetTable<ACCESS>();
			}
		}
		
		public System.Data.Linq.Table<STATUS> STATUS
		{
			get
			{
				return this.GetTable<STATUS>();
			}
		}
		
		public System.Data.Linq.Table<EMP_INFO> EMP_INFOs
		{
			get
			{
				return this.GetTable<EMP_INFO>();
			}
		}
		
		public System.Data.Linq.Table<WORK_TYPE> WORK_TYPEs
		{
			get
			{
				return this.GetTable<WORK_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<EMP_WORK_INFO> EMP_WORK_INFOs
		{
			get
			{
				return this.GetTable<EMP_WORK_INFO>();
			}
		}
		
		public System.Data.Linq.Table<ATTENDANCE> ATTENDANCEs
		{
			get
			{
				return this.GetTable<ATTENDANCE>();
			}
		}
		
		public System.Data.Linq.Table<NFC_NAME_VIEW> NFC_NAME_VIEWs
		{
			get
			{
				return this.GetTable<NFC_NAME_VIEW>();
			}
		}
		
		public System.Data.Linq.Table<NOTICE> NOTICEs
		{
			get
			{
				return this.GetTable<NOTICE>();
			}
		}
		
		public System.Data.Linq.Table<NOTICE_VIEW> NOTICE_VIEWs
		{
			get
			{
				return this.GetTable<NOTICE_VIEW>();
			}
		}
		
		public System.Data.Linq.Table<T_SHIRT_SIZE> T_SHIRT_SIZEs
		{
			get
			{
				return this.GetTable<T_SHIRT_SIZE>();
			}
		}
		
		public System.Data.Linq.Table<T_SHIRT_STOCK> T_SHIRT_STOCKs
		{
			get
			{
				return this.GetTable<T_SHIRT_STOCK>();
			}
		}
		
		public System.Data.Linq.Table<T_SHIRT_NAME> T_SHIRT_NAMEs
		{
			get
			{
				return this.GetTable<T_SHIRT_NAME>();
			}
		}
		
		public System.Data.Linq.Table<T_SHIRT_STATE> T_SHIRT_STATEs
		{
			get
			{
				return this.GetTable<T_SHIRT_STATE>();
			}
		}
		
		public System.Data.Linq.Table<SALE_T_SHIRT> SALE_T_SHIRTs
		{
			get
			{
				return this.GetTable<SALE_T_SHIRT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTMENT")]
	public partial class DEPARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DEP_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDEP_NAMEChanging(string value);
    partial void OnDEP_NAMEChanged();
    #endregion
		
		public DEPARTMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_NAME", DbType="VarChar(50)")]
		public string DEP_NAME
		{
			get
			{
				return this._DEP_NAME;
			}
			set
			{
				if ((this._DEP_NAME != value))
				{
					this.OnDEP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEP_NAME = value;
					this.SendPropertyChanged("DEP_NAME");
					this.OnDEP_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POSITION")]
	public partial class POSITION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_ID;
		
		private string _POSITION_NAME;
		
		private System.Nullable<int> _D_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IDChanging(int value);
    partial void OnP_IDChanged();
    partial void OnPOSITION_NAMEChanging(string value);
    partial void OnPOSITION_NAMEChanged();
    partial void OnD_IDChanging(System.Nullable<int> value);
    partial void OnD_IDChanged();
    #endregion
		
		public POSITION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_NAME", DbType="VarChar(50)")]
		public string POSITION_NAME
		{
			get
			{
				return this._POSITION_NAME;
			}
			set
			{
				if ((this._POSITION_NAME != value))
				{
					this.OnPOSITION_NAMEChanging(value);
					this.SendPropertyChanging();
					this._POSITION_NAME = value;
					this.SendPropertyChanged("POSITION_NAME");
					this.OnPOSITION_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_ID", DbType="Int")]
		public System.Nullable<int> D_ID
		{
			get
			{
				return this._D_ID;
			}
			set
			{
				if ((this._D_ID != value))
				{
					this.OnD_IDChanging(value);
					this.SendPropertyChanging();
					this._D_ID = value;
					this.SendPropertyChanged("D_ID");
					this.OnD_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BLOOD_GROUP")]
	public partial class BLOOD_GROUP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _B_ID;
		
		private string _BLOOD_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnB_IDChanging(int value);
    partial void OnB_IDChanged();
    partial void OnBLOOD_NAMEChanging(string value);
    partial void OnBLOOD_NAMEChanged();
    #endregion
		
		public BLOOD_GROUP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int B_ID
		{
			get
			{
				return this._B_ID;
			}
			set
			{
				if ((this._B_ID != value))
				{
					this.OnB_IDChanging(value);
					this.SendPropertyChanging();
					this._B_ID = value;
					this.SendPropertyChanged("B_ID");
					this.OnB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD_NAME", DbType="VarChar(10)")]
		public string BLOOD_NAME
		{
			get
			{
				return this._BLOOD_NAME;
			}
			set
			{
				if ((this._BLOOD_NAME != value))
				{
					this.OnBLOOD_NAMEChanging(value);
					this.SendPropertyChanging();
					this._BLOOD_NAME = value;
					this.SendPropertyChanged("BLOOD_NAME");
					this.OnBLOOD_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LANGUAGE")]
	public partial class LANGUAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _L_ID;
		
		private string _LANGUAGE1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnL_IDChanging(int value);
    partial void OnL_IDChanged();
    partial void OnLANGUAGE1Changing(string value);
    partial void OnLANGUAGE1Changed();
    #endregion
		
		public LANGUAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int L_ID
		{
			get
			{
				return this._L_ID;
			}
			set
			{
				if ((this._L_ID != value))
				{
					this.OnL_IDChanging(value);
					this.SendPropertyChanging();
					this._L_ID = value;
					this.SendPropertyChanged("L_ID");
					this.OnL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LANGUAGE", Storage="_LANGUAGE1", DbType="VarChar(50)")]
		public string LANGUAGE1
		{
			get
			{
				return this._LANGUAGE1;
			}
			set
			{
				if ((this._LANGUAGE1 != value))
				{
					this.OnLANGUAGE1Changing(value);
					this.SendPropertyChanging();
					this._LANGUAGE1 = value;
					this.SendPropertyChanged("LANGUAGE1");
					this.OnLANGUAGE1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GENDER")]
	public partial class GENDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _G_ID;
		
		private string _GENDER1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnG_IDChanging(int value);
    partial void OnG_IDChanged();
    partial void OnGENDER1Changing(string value);
    partial void OnGENDER1Changed();
    #endregion
		
		public GENDER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int G_ID
		{
			get
			{
				return this._G_ID;
			}
			set
			{
				if ((this._G_ID != value))
				{
					this.OnG_IDChanging(value);
					this.SendPropertyChanging();
					this._G_ID = value;
					this.SendPropertyChanged("G_ID");
					this.OnG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="GENDER", Storage="_GENDER1", DbType="VarChar(10)")]
		public string GENDER1
		{
			get
			{
				return this._GENDER1;
			}
			set
			{
				if ((this._GENDER1 != value))
				{
					this.OnGENDER1Changing(value);
					this.SendPropertyChanging();
					this._GENDER1 = value;
					this.SendPropertyChanged("GENDER1");
					this.OnGENDER1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRANCH")]
	public partial class BRANCH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _B_ID;
		
		private string _BRANCH_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnB_IDChanging(int value);
    partial void OnB_IDChanged();
    partial void OnBRANCH_NAMEChanging(string value);
    partial void OnBRANCH_NAMEChanged();
    #endregion
		
		public BRANCH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int B_ID
		{
			get
			{
				return this._B_ID;
			}
			set
			{
				if ((this._B_ID != value))
				{
					this.OnB_IDChanging(value);
					this.SendPropertyChanging();
					this._B_ID = value;
					this.SendPropertyChanged("B_ID");
					this.OnB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NAME", DbType="VarChar(50)")]
		public string BRANCH_NAME
		{
			get
			{
				return this._BRANCH_NAME;
			}
			set
			{
				if ((this._BRANCH_NAME != value))
				{
					this.OnBRANCH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_NAME = value;
					this.SendPropertyChanged("BRANCH_NAME");
					this.OnBRANCH_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PASS")]
	public partial class PASS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private string _USER_NAME;
		
		private string _PASS1;
		
		private System.Nullable<int> _LOG_IN_OUT;
		
		private System.Nullable<int> _LOCK1;
		
		private System.Nullable<int> _LOCK2;
		
		private System.Nullable<int> _CREAT_EMP_ID;
		
		private System.Nullable<System.DateTime> _CREAT_DATE;
		
		private System.Nullable<int> _BRANCH_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMP_IDChanging(System.Nullable<int> value);
    partial void OnEMP_IDChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnPASS1Changing(string value);
    partial void OnPASS1Changed();
    partial void OnLOG_IN_OUTChanging(System.Nullable<int> value);
    partial void OnLOG_IN_OUTChanged();
    partial void OnLOCK1Changing(System.Nullable<int> value);
    partial void OnLOCK1Changed();
    partial void OnLOCK2Changing(System.Nullable<int> value);
    partial void OnLOCK2Changed();
    partial void OnCREAT_EMP_IDChanging(System.Nullable<int> value);
    partial void OnCREAT_EMP_IDChanged();
    partial void OnCREAT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREAT_DATEChanged();
    partial void OnBRANCH_IDChanging(System.Nullable<int> value);
    partial void OnBRANCH_IDChanged();
    #endregion
		
		public PASS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="NVarChar(100)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PASS", Storage="_PASS1", DbType="NVarChar(150)")]
		public string PASS1
		{
			get
			{
				return this._PASS1;
			}
			set
			{
				if ((this._PASS1 != value))
				{
					this.OnPASS1Changing(value);
					this.SendPropertyChanging();
					this._PASS1 = value;
					this.SendPropertyChanged("PASS1");
					this.OnPASS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_IN_OUT", DbType="Int")]
		public System.Nullable<int> LOG_IN_OUT
		{
			get
			{
				return this._LOG_IN_OUT;
			}
			set
			{
				if ((this._LOG_IN_OUT != value))
				{
					this.OnLOG_IN_OUTChanging(value);
					this.SendPropertyChanging();
					this._LOG_IN_OUT = value;
					this.SendPropertyChanged("LOG_IN_OUT");
					this.OnLOG_IN_OUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCK1", DbType="Int")]
		public System.Nullable<int> LOCK1
		{
			get
			{
				return this._LOCK1;
			}
			set
			{
				if ((this._LOCK1 != value))
				{
					this.OnLOCK1Changing(value);
					this.SendPropertyChanging();
					this._LOCK1 = value;
					this.SendPropertyChanged("LOCK1");
					this.OnLOCK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCK2", DbType="Int")]
		public System.Nullable<int> LOCK2
		{
			get
			{
				return this._LOCK2;
			}
			set
			{
				if ((this._LOCK2 != value))
				{
					this.OnLOCK2Changing(value);
					this.SendPropertyChanging();
					this._LOCK2 = value;
					this.SendPropertyChanged("LOCK2");
					this.OnLOCK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREAT_EMP_ID", DbType="Int")]
		public System.Nullable<int> CREAT_EMP_ID
		{
			get
			{
				return this._CREAT_EMP_ID;
			}
			set
			{
				if ((this._CREAT_EMP_ID != value))
				{
					this.OnCREAT_EMP_IDChanging(value);
					this.SendPropertyChanging();
					this._CREAT_EMP_ID = value;
					this.SendPropertyChanged("CREAT_EMP_ID");
					this.OnCREAT_EMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREAT_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CREAT_DATE
		{
			get
			{
				return this._CREAT_DATE;
			}
			set
			{
				if ((this._CREAT_DATE != value))
				{
					this.OnCREAT_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREAT_DATE = value;
					this.SendPropertyChanged("CREAT_DATE");
					this.OnCREAT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ID", DbType="Int")]
		public System.Nullable<int> BRANCH_ID
		{
			get
			{
				return this._BRANCH_ID;
			}
			set
			{
				if ((this._BRANCH_ID != value))
				{
					this.OnBRANCH_IDChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_ID = value;
					this.SendPropertyChanged("BRANCH_ID");
					this.OnBRANCH_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCESS")]
	public partial class ACCESS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private System.Nullable<int> _MENU_A;
		
		private System.Nullable<int> _MENU_B;
		
		private System.Nullable<int> _MENU_C;
		
		private System.Nullable<int> _MENU_D;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMP_IDChanging(System.Nullable<int> value);
    partial void OnEMP_IDChanged();
    partial void OnMENU_AChanging(System.Nullable<int> value);
    partial void OnMENU_AChanged();
    partial void OnMENU_BChanging(System.Nullable<int> value);
    partial void OnMENU_BChanged();
    partial void OnMENU_CChanging(System.Nullable<int> value);
    partial void OnMENU_CChanged();
    partial void OnMENU_DChanging(System.Nullable<int> value);
    partial void OnMENU_DChanged();
    #endregion
		
		public ACCESS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_A", DbType="Int")]
		public System.Nullable<int> MENU_A
		{
			get
			{
				return this._MENU_A;
			}
			set
			{
				if ((this._MENU_A != value))
				{
					this.OnMENU_AChanging(value);
					this.SendPropertyChanging();
					this._MENU_A = value;
					this.SendPropertyChanged("MENU_A");
					this.OnMENU_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_B", DbType="Int")]
		public System.Nullable<int> MENU_B
		{
			get
			{
				return this._MENU_B;
			}
			set
			{
				if ((this._MENU_B != value))
				{
					this.OnMENU_BChanging(value);
					this.SendPropertyChanging();
					this._MENU_B = value;
					this.SendPropertyChanged("MENU_B");
					this.OnMENU_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_C", DbType="Int")]
		public System.Nullable<int> MENU_C
		{
			get
			{
				return this._MENU_C;
			}
			set
			{
				if ((this._MENU_C != value))
				{
					this.OnMENU_CChanging(value);
					this.SendPropertyChanging();
					this._MENU_C = value;
					this.SendPropertyChanged("MENU_C");
					this.OnMENU_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_D", DbType="Int")]
		public System.Nullable<int> MENU_D
		{
			get
			{
				return this._MENU_D;
			}
			set
			{
				if ((this._MENU_D != value))
				{
					this.OnMENU_DChanging(value);
					this.SendPropertyChanging();
					this._MENU_D = value;
					this.SendPropertyChanged("MENU_D");
					this.OnMENU_DChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATUS")]
	public partial class STATUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _STATUS1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSTATUS1Changing(string value);
    partial void OnSTATUS1Changed();
    #endregion
		
		public STATUS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="STATUS", Storage="_STATUS1", DbType="VarChar(15)")]
		public string STATUS1
		{
			get
			{
				return this._STATUS1;
			}
			set
			{
				if ((this._STATUS1 != value))
				{
					this.OnSTATUS1Changing(value);
					this.SendPropertyChanging();
					this._STATUS1 = value;
					this.SendPropertyChanged("STATUS1");
					this.OnSTATUS1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMP_INFO")]
	public partial class EMP_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMP_ID;
		
		private string _FRIST_NAME;
		
		private string _NAME_SURENAME;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<int> _MOBILE;
		
		private string _NIC;
		
		private string _EMAIL;
		
		private System.Nullable<int> _BLOOD_ID;
		
		private string _ADDRESS;
		
		private System.Nullable<int> _GENDER;
		
		private System.Nullable<int> _CREATE_EMP_ID;
		
		private System.Nullable<System.DateTime> _EMP_CREATE_DATE;
		
		private System.Nullable<int> _LANGUAGE;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMP_IDChanging(int value);
    partial void OnEMP_IDChanged();
    partial void OnFRIST_NAMEChanging(string value);
    partial void OnFRIST_NAMEChanged();
    partial void OnNAME_SURENAMEChanging(string value);
    partial void OnNAME_SURENAMEChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnMOBILEChanging(System.Nullable<int> value);
    partial void OnMOBILEChanged();
    partial void OnNICChanging(string value);
    partial void OnNICChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnBLOOD_IDChanging(System.Nullable<int> value);
    partial void OnBLOOD_IDChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnGENDERChanging(System.Nullable<int> value);
    partial void OnGENDERChanged();
    partial void OnCREATE_EMP_IDChanging(System.Nullable<int> value);
    partial void OnCREATE_EMP_IDChanged();
    partial void OnEMP_CREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_CREATE_DATEChanged();
    partial void OnLANGUAGEChanging(System.Nullable<int> value);
    partial void OnLANGUAGEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public EMP_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRIST_NAME", DbType="NVarChar(50)")]
		public string FRIST_NAME
		{
			get
			{
				return this._FRIST_NAME;
			}
			set
			{
				if ((this._FRIST_NAME != value))
				{
					this.OnFRIST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FRIST_NAME = value;
					this.SendPropertyChanged("FRIST_NAME");
					this.OnFRIST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_SURENAME", DbType="NVarChar(50)")]
		public string NAME_SURENAME
		{
			get
			{
				return this._NAME_SURENAME;
			}
			set
			{
				if ((this._NAME_SURENAME != value))
				{
					this.OnNAME_SURENAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME_SURENAME = value;
					this.SendPropertyChanged("NAME_SURENAME");
					this.OnNAME_SURENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="Int")]
		public System.Nullable<int> MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this.OnMOBILEChanging(value);
					this.SendPropertyChanging();
					this._MOBILE = value;
					this.SendPropertyChanged("MOBILE");
					this.OnMOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIC", DbType="NVarChar(50)")]
		public string NIC
		{
			get
			{
				return this._NIC;
			}
			set
			{
				if ((this._NIC != value))
				{
					this.OnNICChanging(value);
					this.SendPropertyChanging();
					this._NIC = value;
					this.SendPropertyChanged("NIC");
					this.OnNICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD_ID", DbType="Int")]
		public System.Nullable<int> BLOOD_ID
		{
			get
			{
				return this._BLOOD_ID;
			}
			set
			{
				if ((this._BLOOD_ID != value))
				{
					this.OnBLOOD_IDChanging(value);
					this.SendPropertyChanging();
					this._BLOOD_ID = value;
					this.SendPropertyChanged("BLOOD_ID");
					this.OnBLOOD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(100)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="Int")]
		public System.Nullable<int> GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this.OnGENDERChanging(value);
					this.SendPropertyChanging();
					this._GENDER = value;
					this.SendPropertyChanged("GENDER");
					this.OnGENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_EMP_ID", DbType="Int")]
		public System.Nullable<int> CREATE_EMP_ID
		{
			get
			{
				return this._CREATE_EMP_ID;
			}
			set
			{
				if ((this._CREATE_EMP_ID != value))
				{
					this.OnCREATE_EMP_IDChanging(value);
					this.SendPropertyChanging();
					this._CREATE_EMP_ID = value;
					this.SendPropertyChanged("CREATE_EMP_ID");
					this.OnCREATE_EMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CREATE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> EMP_CREATE_DATE
		{
			get
			{
				return this._EMP_CREATE_DATE;
			}
			set
			{
				if ((this._EMP_CREATE_DATE != value))
				{
					this.OnEMP_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._EMP_CREATE_DATE = value;
					this.SendPropertyChanged("EMP_CREATE_DATE");
					this.OnEMP_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANGUAGE", DbType="Int")]
		public System.Nullable<int> LANGUAGE
		{
			get
			{
				return this._LANGUAGE;
			}
			set
			{
				if ((this._LANGUAGE != value))
				{
					this.OnLANGUAGEChanging(value);
					this.SendPropertyChanging();
					this._LANGUAGE = value;
					this.SendPropertyChanged("LANGUAGE");
					this.OnLANGUAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WORK_TYPE")]
	public partial class WORK_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _W_ID;
		
		private string _W_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnW_IDChanging(int value);
    partial void OnW_IDChanged();
    partial void OnW_NAMEChanging(string value);
    partial void OnW_NAMEChanged();
    #endregion
		
		public WORK_TYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int W_ID
		{
			get
			{
				return this._W_ID;
			}
			set
			{
				if ((this._W_ID != value))
				{
					this.OnW_IDChanging(value);
					this.SendPropertyChanging();
					this._W_ID = value;
					this.SendPropertyChanged("W_ID");
					this.OnW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string W_NAME
		{
			get
			{
				return this._W_NAME;
			}
			set
			{
				if ((this._W_NAME != value))
				{
					this.OnW_NAMEChanging(value);
					this.SendPropertyChanging();
					this._W_NAME = value;
					this.SendPropertyChanged("W_NAME");
					this.OnW_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMP_WORK_INFO")]
	public partial class EMP_WORK_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private System.Nullable<int> _B_ID;
		
		private System.Nullable<int> _RE_EMP_ID;
		
		private string _DESCRIPTION;
		
		private System.Nullable<int> _W_T_ID;
		
		private System.Nullable<int> _P_ID;
		
		private System.Nullable<int> _D_ID;
		
		private System.Nullable<System.DateTime> _D_OF_A;
		
		private System.Nullable<System.DateTime> _D_OF_C;
		
		private System.Nullable<System.DateTime> _D_OF_JOIN;
		
		private string _NFC_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMP_IDChanging(System.Nullable<int> value);
    partial void OnEMP_IDChanged();
    partial void OnB_IDChanging(System.Nullable<int> value);
    partial void OnB_IDChanged();
    partial void OnRE_EMP_IDChanging(System.Nullable<int> value);
    partial void OnRE_EMP_IDChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnW_T_IDChanging(System.Nullable<int> value);
    partial void OnW_T_IDChanged();
    partial void OnP_IDChanging(System.Nullable<int> value);
    partial void OnP_IDChanged();
    partial void OnD_IDChanging(System.Nullable<int> value);
    partial void OnD_IDChanged();
    partial void OnD_OF_AChanging(System.Nullable<System.DateTime> value);
    partial void OnD_OF_AChanged();
    partial void OnD_OF_CChanging(System.Nullable<System.DateTime> value);
    partial void OnD_OF_CChanged();
    partial void OnD_OF_JOINChanging(System.Nullable<System.DateTime> value);
    partial void OnD_OF_JOINChanged();
    partial void OnNFC_NUMBERChanging(string value);
    partial void OnNFC_NUMBERChanged();
    #endregion
		
		public EMP_WORK_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_ID", DbType="Int")]
		public System.Nullable<int> B_ID
		{
			get
			{
				return this._B_ID;
			}
			set
			{
				if ((this._B_ID != value))
				{
					this.OnB_IDChanging(value);
					this.SendPropertyChanging();
					this._B_ID = value;
					this.SendPropertyChanged("B_ID");
					this.OnB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_EMP_ID", DbType="Int")]
		public System.Nullable<int> RE_EMP_ID
		{
			get
			{
				return this._RE_EMP_ID;
			}
			set
			{
				if ((this._RE_EMP_ID != value))
				{
					this.OnRE_EMP_IDChanging(value);
					this.SendPropertyChanging();
					this._RE_EMP_ID = value;
					this.SendPropertyChanged("RE_EMP_ID");
					this.OnRE_EMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(250)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W_T_ID", DbType="Int")]
		public System.Nullable<int> W_T_ID
		{
			get
			{
				return this._W_T_ID;
			}
			set
			{
				if ((this._W_T_ID != value))
				{
					this.OnW_T_IDChanging(value);
					this.SendPropertyChanging();
					this._W_T_ID = value;
					this.SendPropertyChanged("W_T_ID");
					this.OnW_T_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_ID", DbType="Int")]
		public System.Nullable<int> D_ID
		{
			get
			{
				return this._D_ID;
			}
			set
			{
				if ((this._D_ID != value))
				{
					this.OnD_IDChanging(value);
					this.SendPropertyChanging();
					this._D_ID = value;
					this.SendPropertyChanged("D_ID");
					this.OnD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[D/OF_A]", Storage="_D_OF_A", DbType="Date")]
		public System.Nullable<System.DateTime> D_OF_A
		{
			get
			{
				return this._D_OF_A;
			}
			set
			{
				if ((this._D_OF_A != value))
				{
					this.OnD_OF_AChanging(value);
					this.SendPropertyChanging();
					this._D_OF_A = value;
					this.SendPropertyChanged("D_OF_A");
					this.OnD_OF_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[D/OF_C]", Storage="_D_OF_C", DbType="Date")]
		public System.Nullable<System.DateTime> D_OF_C
		{
			get
			{
				return this._D_OF_C;
			}
			set
			{
				if ((this._D_OF_C != value))
				{
					this.OnD_OF_CChanging(value);
					this.SendPropertyChanging();
					this._D_OF_C = value;
					this.SendPropertyChanged("D_OF_C");
					this.OnD_OF_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[D/OF_JOIN]", Storage="_D_OF_JOIN", DbType="Date")]
		public System.Nullable<System.DateTime> D_OF_JOIN
		{
			get
			{
				return this._D_OF_JOIN;
			}
			set
			{
				if ((this._D_OF_JOIN != value))
				{
					this.OnD_OF_JOINChanging(value);
					this.SendPropertyChanging();
					this._D_OF_JOIN = value;
					this.SendPropertyChanged("D_OF_JOIN");
					this.OnD_OF_JOINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NFC_NUMBER", DbType="VarChar(100)")]
		public string NFC_NUMBER
		{
			get
			{
				return this._NFC_NUMBER;
			}
			set
			{
				if ((this._NFC_NUMBER != value))
				{
					this.OnNFC_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._NFC_NUMBER = value;
					this.SendPropertyChanged("NFC_NUMBER");
					this.OnNFC_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ATTENDANCE")]
	public partial class ATTENDANCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CODE;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<System.DateTime> _IN_TIME;
		
		private System.Nullable<System.DateTime> _OUT_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCODEChanging(System.Nullable<int> value);
    partial void OnCODEChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnIN_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnIN_TIMEChanged();
    partial void OnOUT_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnOUT_TIMEChanged();
    #endregion
		
		public ATTENDANCE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="Int")]
		public System.Nullable<int> CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> IN_TIME
		{
			get
			{
				return this._IN_TIME;
			}
			set
			{
				if ((this._IN_TIME != value))
				{
					this.OnIN_TIMEChanging(value);
					this.SendPropertyChanging();
					this._IN_TIME = value;
					this.SendPropertyChanged("IN_TIME");
					this.OnIN_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> OUT_TIME
		{
			get
			{
				return this._OUT_TIME;
			}
			set
			{
				if ((this._OUT_TIME != value))
				{
					this.OnOUT_TIMEChanging(value);
					this.SendPropertyChanging();
					this._OUT_TIME = value;
					this.SendPropertyChanged("OUT_TIME");
					this.OnOUT_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFC_NAME_VIEW")]
	public partial class NFC_NAME_VIEW
	{
		
		private string _NAME_SURENAME;
		
		private string _NFC_NUMBER;
		
		private System.Nullable<int> _EMP_ID;
		
		private string _FRIST_NAME;
		
		public NFC_NAME_VIEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_SURENAME", DbType="NVarChar(50)")]
		public string NAME_SURENAME
		{
			get
			{
				return this._NAME_SURENAME;
			}
			set
			{
				if ((this._NAME_SURENAME != value))
				{
					this._NAME_SURENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NFC_NUMBER", DbType="NVarChar(50)")]
		public string NFC_NUMBER
		{
			get
			{
				return this._NFC_NUMBER;
			}
			set
			{
				if ((this._NFC_NUMBER != value))
				{
					this._NFC_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this._EMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRIST_NAME", DbType="NVarChar(50)")]
		public string FRIST_NAME
		{
			get
			{
				return this._FRIST_NAME;
			}
			set
			{
				if ((this._FRIST_NAME != value))
				{
					this._FRIST_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOTICE")]
	public partial class NOTICE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NO_ID;
		
		private System.Nullable<int> _D_ID;
		
		private System.Nullable<int> _P_ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private System.Nullable<System.DateTime> _TO_DATE;
		
		private System.Nullable<System.DateTime> _FROM;
		
		private string _N_TITEL;
		
		private string _N_BODY;
		
		private System.Nullable<int> _N_PUT_ID;
		
		private System.Nullable<int> _N_FROM_ALL;
		
		private System.Nullable<int> _PUT_P_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNO_IDChanging(int value);
    partial void OnNO_IDChanged();
    partial void OnD_IDChanging(System.Nullable<int> value);
    partial void OnD_IDChanged();
    partial void OnP_IDChanging(System.Nullable<int> value);
    partial void OnP_IDChanged();
    partial void OnEMP_IDChanging(System.Nullable<int> value);
    partial void OnEMP_IDChanged();
    partial void OnTO_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTO_DATEChanged();
    partial void OnFROMChanging(System.Nullable<System.DateTime> value);
    partial void OnFROMChanged();
    partial void OnN_TITELChanging(string value);
    partial void OnN_TITELChanged();
    partial void OnN_BODYChanging(string value);
    partial void OnN_BODYChanged();
    partial void OnN_PUT_IDChanging(System.Nullable<int> value);
    partial void OnN_PUT_IDChanged();
    partial void OnN_FROM_ALLChanging(System.Nullable<int> value);
    partial void OnN_FROM_ALLChanged();
    partial void OnPUT_P_IDChanging(System.Nullable<int> value);
    partial void OnPUT_P_IDChanged();
    #endregion
		
		public NOTICE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NO_ID
		{
			get
			{
				return this._NO_ID;
			}
			set
			{
				if ((this._NO_ID != value))
				{
					this.OnNO_IDChanging(value);
					this.SendPropertyChanging();
					this._NO_ID = value;
					this.SendPropertyChanged("NO_ID");
					this.OnNO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_ID", DbType="Int")]
		public System.Nullable<int> D_ID
		{
			get
			{
				return this._D_ID;
			}
			set
			{
				if ((this._D_ID != value))
				{
					this.OnD_IDChanging(value);
					this.SendPropertyChanging();
					this._D_ID = value;
					this.SendPropertyChanged("D_ID");
					this.OnD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> TO_DATE
		{
			get
			{
				return this._TO_DATE;
			}
			set
			{
				if ((this._TO_DATE != value))
				{
					this.OnTO_DATEChanging(value);
					this.SendPropertyChanging();
					this._TO_DATE = value;
					this.SendPropertyChanged("TO_DATE");
					this.OnTO_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FROM]", Storage="_FROM", DbType="Date")]
		public System.Nullable<System.DateTime> FROM
		{
			get
			{
				return this._FROM;
			}
			set
			{
				if ((this._FROM != value))
				{
					this.OnFROMChanging(value);
					this.SendPropertyChanging();
					this._FROM = value;
					this.SendPropertyChanged("FROM");
					this.OnFROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_TITEL", DbType="NVarChar(100)")]
		public string N_TITEL
		{
			get
			{
				return this._N_TITEL;
			}
			set
			{
				if ((this._N_TITEL != value))
				{
					this.OnN_TITELChanging(value);
					this.SendPropertyChanging();
					this._N_TITEL = value;
					this.SendPropertyChanged("N_TITEL");
					this.OnN_TITELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_BODY", DbType="NVarChar(500)")]
		public string N_BODY
		{
			get
			{
				return this._N_BODY;
			}
			set
			{
				if ((this._N_BODY != value))
				{
					this.OnN_BODYChanging(value);
					this.SendPropertyChanging();
					this._N_BODY = value;
					this.SendPropertyChanged("N_BODY");
					this.OnN_BODYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_PUT_ID", DbType="Int")]
		public System.Nullable<int> N_PUT_ID
		{
			get
			{
				return this._N_PUT_ID;
			}
			set
			{
				if ((this._N_PUT_ID != value))
				{
					this.OnN_PUT_IDChanging(value);
					this.SendPropertyChanging();
					this._N_PUT_ID = value;
					this.SendPropertyChanged("N_PUT_ID");
					this.OnN_PUT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_FROM_ALL", DbType="Int")]
		public System.Nullable<int> N_FROM_ALL
		{
			get
			{
				return this._N_FROM_ALL;
			}
			set
			{
				if ((this._N_FROM_ALL != value))
				{
					this.OnN_FROM_ALLChanging(value);
					this.SendPropertyChanging();
					this._N_FROM_ALL = value;
					this.SendPropertyChanged("N_FROM_ALL");
					this.OnN_FROM_ALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUT_P_ID", DbType="Int")]
		public System.Nullable<int> PUT_P_ID
		{
			get
			{
				return this._PUT_P_ID;
			}
			set
			{
				if ((this._PUT_P_ID != value))
				{
					this.OnPUT_P_IDChanging(value);
					this.SendPropertyChanging();
					this._PUT_P_ID = value;
					this.SendPropertyChanged("PUT_P_ID");
					this.OnPUT_P_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOTICE_VIEW")]
	public partial class NOTICE_VIEW
	{
		
		private int _NO_ID;
		
		private string _N_TITEL;
		
		private string _POSITION_NAME;
		
		private string _NAME_SURENAME;
		
		private System.Nullable<int> _D_ID;
		
		private System.Nullable<int> _P_ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private System.Nullable<System.DateTime> _FROM;
		
		public NOTICE_VIEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_ID", DbType="Int NOT NULL")]
		public int NO_ID
		{
			get
			{
				return this._NO_ID;
			}
			set
			{
				if ((this._NO_ID != value))
				{
					this._NO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_TITEL", DbType="NVarChar(100)")]
		public string N_TITEL
		{
			get
			{
				return this._N_TITEL;
			}
			set
			{
				if ((this._N_TITEL != value))
				{
					this._N_TITEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_NAME", DbType="VarChar(50)")]
		public string POSITION_NAME
		{
			get
			{
				return this._POSITION_NAME;
			}
			set
			{
				if ((this._POSITION_NAME != value))
				{
					this._POSITION_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_SURENAME", DbType="NVarChar(50)")]
		public string NAME_SURENAME
		{
			get
			{
				return this._NAME_SURENAME;
			}
			set
			{
				if ((this._NAME_SURENAME != value))
				{
					this._NAME_SURENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_ID", DbType="Int")]
		public System.Nullable<int> D_ID
		{
			get
			{
				return this._D_ID;
			}
			set
			{
				if ((this._D_ID != value))
				{
					this._D_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this._P_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this._EMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FROM]", Storage="_FROM", DbType="Date")]
		public System.Nullable<System.DateTime> FROM
		{
			get
			{
				return this._FROM;
			}
			set
			{
				if ((this._FROM != value))
				{
					this._FROM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SHIRT_SIZE")]
	public partial class T_SHIRT_SIZE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SIZE_ID;
		
		private string _SIZE_NAME;
		
		private System.Nullable<decimal> _LENGTH;
		
		private System.Nullable<decimal> _WIDTH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIZE_IDChanging(int value);
    partial void OnSIZE_IDChanged();
    partial void OnSIZE_NAMEChanging(string value);
    partial void OnSIZE_NAMEChanged();
    partial void OnLENGTHChanging(System.Nullable<decimal> value);
    partial void OnLENGTHChanged();
    partial void OnWIDTHChanging(System.Nullable<decimal> value);
    partial void OnWIDTHChanged();
    #endregion
		
		public T_SHIRT_SIZE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SIZE_ID
		{
			get
			{
				return this._SIZE_ID;
			}
			set
			{
				if ((this._SIZE_ID != value))
				{
					this.OnSIZE_IDChanging(value);
					this.SendPropertyChanging();
					this._SIZE_ID = value;
					this.SendPropertyChanged("SIZE_ID");
					this.OnSIZE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE_NAME", DbType="NVarChar(50)")]
		public string SIZE_NAME
		{
			get
			{
				return this._SIZE_NAME;
			}
			set
			{
				if ((this._SIZE_NAME != value))
				{
					this.OnSIZE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SIZE_NAME = value;
					this.SendPropertyChanged("SIZE_NAME");
					this.OnSIZE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LENGTH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LENGTH
		{
			get
			{
				return this._LENGTH;
			}
			set
			{
				if ((this._LENGTH != value))
				{
					this.OnLENGTHChanging(value);
					this.SendPropertyChanging();
					this._LENGTH = value;
					this.SendPropertyChanged("LENGTH");
					this.OnLENGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIDTH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> WIDTH
		{
			get
			{
				return this._WIDTH;
			}
			set
			{
				if ((this._WIDTH != value))
				{
					this.OnWIDTHChanging(value);
					this.SendPropertyChanging();
					this._WIDTH = value;
					this.SendPropertyChanged("WIDTH");
					this.OnWIDTHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SHIRT_STOCK")]
	public partial class T_SHIRT_STOCK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _T_S_N_ID;
		
		private System.Nullable<int> _T_S_SIZE_ID;
		
		private System.Nullable<int> _T_STOCK_QUANTITY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnT_S_N_IDChanging(System.Nullable<int> value);
    partial void OnT_S_N_IDChanged();
    partial void OnT_S_SIZE_IDChanging(System.Nullable<int> value);
    partial void OnT_S_SIZE_IDChanged();
    partial void OnT_STOCK_QUANTITYChanging(System.Nullable<int> value);
    partial void OnT_STOCK_QUANTITYChanged();
    #endregion
		
		public T_SHIRT_STOCK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_S_N_ID", DbType="Int")]
		public System.Nullable<int> T_S_N_ID
		{
			get
			{
				return this._T_S_N_ID;
			}
			set
			{
				if ((this._T_S_N_ID != value))
				{
					this.OnT_S_N_IDChanging(value);
					this.SendPropertyChanging();
					this._T_S_N_ID = value;
					this.SendPropertyChanged("T_S_N_ID");
					this.OnT_S_N_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_S_SIZE_ID", DbType="Int")]
		public System.Nullable<int> T_S_SIZE_ID
		{
			get
			{
				return this._T_S_SIZE_ID;
			}
			set
			{
				if ((this._T_S_SIZE_ID != value))
				{
					this.OnT_S_SIZE_IDChanging(value);
					this.SendPropertyChanging();
					this._T_S_SIZE_ID = value;
					this.SendPropertyChanged("T_S_SIZE_ID");
					this.OnT_S_SIZE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_STOCK_QUANTITY", DbType="Int")]
		public System.Nullable<int> T_STOCK_QUANTITY
		{
			get
			{
				return this._T_STOCK_QUANTITY;
			}
			set
			{
				if ((this._T_STOCK_QUANTITY != value))
				{
					this.OnT_STOCK_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._T_STOCK_QUANTITY = value;
					this.SendPropertyChanged("T_STOCK_QUANTITY");
					this.OnT_STOCK_QUANTITYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SHIRT_NAME")]
	public partial class T_SHIRT_NAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _T_NAME;
		
		private System.Nullable<decimal> _PRICE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnT_NAMEChanging(string value);
    partial void OnT_NAMEChanged();
    partial void OnPRICEChanging(System.Nullable<decimal> value);
    partial void OnPRICEChanged();
    #endregion
		
		public T_SHIRT_NAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_NAME", DbType="NVarChar(50)")]
		public string T_NAME
		{
			get
			{
				return this._T_NAME;
			}
			set
			{
				if ((this._T_NAME != value))
				{
					this.OnT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._T_NAME = value;
					this.SendPropertyChanged("T_NAME");
					this.OnT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Money")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SHIRT_STATES")]
	public partial class T_SHIRT_STATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _T_STATES;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnT_STATESChanging(string value);
    partial void OnT_STATESChanged();
    #endregion
		
		public T_SHIRT_STATE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_STATES", DbType="NVarChar(50)")]
		public string T_STATES
		{
			get
			{
				return this._T_STATES;
			}
			set
			{
				if ((this._T_STATES != value))
				{
					this.OnT_STATESChanging(value);
					this.SendPropertyChanging();
					this._T_STATES = value;
					this.SendPropertyChanged("T_STATES");
					this.OnT_STATESChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALE_T_SHIRT")]
	public partial class SALE_T_SHIRT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _EMP_ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<int> _B_ID;
		
		private string _RESIPT_NO;
		
		private System.Nullable<int> _STATES;
		
		private System.Nullable<int> _QUANTITY;
		
		private System.Nullable<int> _ODER_ID;
		
		private System.Nullable<int> _T_S_N_ID;
		
		private System.Nullable<int> _T_S_SIZE_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMP_IDChanging(System.Nullable<int> value);
    partial void OnEMP_IDChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnB_IDChanging(System.Nullable<int> value);
    partial void OnB_IDChanged();
    partial void OnRESIPT_NOChanging(string value);
    partial void OnRESIPT_NOChanged();
    partial void OnSTATESChanging(System.Nullable<int> value);
    partial void OnSTATESChanged();
    partial void OnQUANTITYChanging(System.Nullable<int> value);
    partial void OnQUANTITYChanged();
    partial void OnODER_IDChanging(System.Nullable<int> value);
    partial void OnODER_IDChanged();
    partial void OnT_S_N_IDChanging(System.Nullable<int> value);
    partial void OnT_S_N_IDChanged();
    partial void OnT_S_SIZE_IDChanging(System.Nullable<int> value);
    partial void OnT_S_SIZE_IDChanged();
    #endregion
		
		public SALE_T_SHIRT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="Int")]
		public System.Nullable<int> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_ID", DbType="Int")]
		public System.Nullable<int> B_ID
		{
			get
			{
				return this._B_ID;
			}
			set
			{
				if ((this._B_ID != value))
				{
					this.OnB_IDChanging(value);
					this.SendPropertyChanging();
					this._B_ID = value;
					this.SendPropertyChanged("B_ID");
					this.OnB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIPT_NO", DbType="NVarChar(50)")]
		public string RESIPT_NO
		{
			get
			{
				return this._RESIPT_NO;
			}
			set
			{
				if ((this._RESIPT_NO != value))
				{
					this.OnRESIPT_NOChanging(value);
					this.SendPropertyChanging();
					this._RESIPT_NO = value;
					this.SendPropertyChanged("RESIPT_NO");
					this.OnRESIPT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATES", DbType="Int")]
		public System.Nullable<int> STATES
		{
			get
			{
				return this._STATES;
			}
			set
			{
				if ((this._STATES != value))
				{
					this.OnSTATESChanging(value);
					this.SendPropertyChanging();
					this._STATES = value;
					this.SendPropertyChanged("STATES");
					this.OnSTATESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int")]
		public System.Nullable<int> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODER_ID", DbType="Int")]
		public System.Nullable<int> ODER_ID
		{
			get
			{
				return this._ODER_ID;
			}
			set
			{
				if ((this._ODER_ID != value))
				{
					this.OnODER_IDChanging(value);
					this.SendPropertyChanging();
					this._ODER_ID = value;
					this.SendPropertyChanged("ODER_ID");
					this.OnODER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_S_N_ID", DbType="Int")]
		public System.Nullable<int> T_S_N_ID
		{
			get
			{
				return this._T_S_N_ID;
			}
			set
			{
				if ((this._T_S_N_ID != value))
				{
					this.OnT_S_N_IDChanging(value);
					this.SendPropertyChanging();
					this._T_S_N_ID = value;
					this.SendPropertyChanged("T_S_N_ID");
					this.OnT_S_N_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_S_SIZE_ID", DbType="Int")]
		public System.Nullable<int> T_S_SIZE_ID
		{
			get
			{
				return this._T_S_SIZE_ID;
			}
			set
			{
				if ((this._T_S_SIZE_ID != value))
				{
					this.OnT_S_SIZE_IDChanging(value);
					this.SendPropertyChanging();
					this._T_S_SIZE_ID = value;
					this.SendPropertyChanged("T_S_SIZE_ID");
					this.OnT_S_SIZE_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
